fix catching 'error' w grep, not screwing my log output

diff --git a/.github/workflows/jira-reporting-actions.yml b/.github/workflows/jira-reporting-actions.yml
--- a/.github/workflows/jira-reporting-actions.yml
+++ b/.github/workflows/jira-reporting-actions.yml
@@ -30,7 +30,7 @@ jobs:
            echo "Update Jira with dependency tree in the changed files: "
            for file in ${{ steps.changed-files-eol.outputs.all_changed_files }}; do
              echo "Changed payload file: $file"
-             bash ./JiraReporting/jqUpdateJson.sh $file 
+             if bash ./JiraReporting/jqUpdateJson.sh $file | grep -i 'error'; then echo '::set-output name=ErrorsFound::NOK'; || true fi 
            done
       - name: Error handling
         if: ${{ steps.use-changed-files.outputs.ErrorsFound == 'NOK' }}
